os: linux
dist: bionic
cache:
    pip: true
language: python
branches:
    only:
        - master
notifications:
    email: false

jobs:
    fast_finish: true
    include:
        - python: '3.6'
        - python: '3.7'
        - python: '3.8'
          name: 'Mypy, Coverage, Test'
          script:
              - sh -c 'mypy --python-executable="$(which python)" -p emitter'
              - time catchsegv coverage run -m unittest discover -s tests
          after_success:
              - bash <(curl -s https://codecov.io/bash)
        - python: '3.9-dev'

before_install:
    - set -e
    - pip --no-cache install -U pip setuptools

install:
    - pip install -qe ".[tests]"

script:
    - catchsegv python -m unittest discover -s tests
